### ISSUE TITLE
Pull in error handling from fast_xor

### ISSUE THREAD

**Issue by SamSaffron** [fny/xorcist#4]
see: https://github.com/CodeMonkeySteve/fast_xor/blob/master/ext/xor/xor.c

```
irb(main):004:0> class A; end
=> nil
irb(main):005:0> Xorcist.xor(A,A)
=> #<Class:0x00007f1d3fed92f8>
```

This is a security issue cause you could causing segfaults here.

**Comment by fny** [comment]
The type checks have been added (see https://github.com/fny/xorcist/blob/master/ext/xorcist/xorcist.c#L15-L23), and a new gem will be cut shortly.

**Comment by SamSaffron** [comment]
wow, awesome, thanks
