### ISSUE TITLE
Recommend JRuby 9.2.7 if you keep refinements

### ISSUE THREAD

**Issue by headius** [fny/xorcist#7]
Hey, @enebo pointed me to your README where you mention JRuby failing the build because of refinements. I've been working in getting refinements working better, so I figured I'd see if xorcist works better on JRuby master (which will be 9.2.7):

```
[] ~/projects/xorcist $ bundle exec rake
Run options: --seed 8423

# Running:

........

Fabulous run in 0.021027s, 380.4612 runs/s, 903.5954 assertions/s.

8 runs, 19 assertions, 0 failures, 0 errors, 0 skips

[] ~/projects/xorcist $ jruby -v
jruby 9.2.7.0-SNAPSHOT (2.5.3) 2019-03-05 2c4518f OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
```

So you should be good to go using refinements on JRuby 9.2.7 or higher. If you decide to keep the refinements, do update the README to mention that requirement.

Thank you!

**Comment by fny** [comment]
Thanks for the update! I just added it to the Travis suite for whenever the release is cut. Do you hav a time frame when I should look back?

Travis is also screaming about some issues with an older version of bundler that I'll need to sift through as well.

**Comment by enebo** [comment]
@fny we should be releasing 9.2.7.0 next week barring any snags.

**Comment by fny** [comment]
Hey all, just an update.

I've decided to keep refinements since it looks like others in the community are already using them: https://github.com/swisscom/ruby-netsnmp

Also, I've tested JRuby 9.2.7 on my computer, and all tests pass. I'm battling with a Travis CI issue now where JRuby 9.2.7 has difficulty being installed.
